window.TRIP_DATA = {
  "title": "USA Father & Son Trip 2026",
  "subtitle": "Ami + Omer | New York + West Coast | 17 Sep – 4 Oct 2026",
  "passenger": "Ami + Omer (13)",
  "finalFlight": "Omer — EL AL LY106 LAX → TLV, 3 Oct 2026 23:00; father returns rental at LAS 4 Oct 14:00",
  "itinerary": [
    {
      "Date": "01-Oct-2026",
      "Day": "Thu",
      "Start time": "05:45",
      "End time": "06:15",
      "Origin / departure point": "Mammoth",
      "Origin address": "",
      "Destination / activity": "Breakfast + depart",
      "Destination address": "Mammoth Mountain Inn",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "30m",
      "Plan / key stops": "Food and water in car",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Tioga day"
    },
    {
      "Date": "01-Oct-2026",
      "Day": "Thu",
      "Start time": "06:15",
      "End time": "07:30",
      "Origin / departure point": "Mammoth",
      "Origin address": "",
      "Destination / activity": "Lee Vining + Tioga entrance",
      "Destination address": "Tioga Pass Entrance",
      "Drive time": "~1h15",
      "Drive distance (mi)": "55",
      "Buffer / activity time": "1h15",
      "Plan / key stops": "Enter only if road open",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "HIGH RISK CHECK",
      "Source / note": "NPS current status OPEN; verify 30/9 + 1/10"
    },
    {
      "Date": "01-Oct-2026",
      "Day": "Thu",
      "Start time": "07:30",
      "End time": "09:00",
      "Origin / departure point": "Tioga Road",
      "Origin address": "",
      "Destination / activity": "Tuolumne / Tenaya / Olmsted stops",
      "Destination address": "Tioga Road",
      "Drive time": "~1h30",
      "Drive distance (mi)": "30",
      "Buffer / activity time": "1h30",
      "Plan / key stops": "Tuolumne optional; Tenaya + Olmsted",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED IF OPEN",
      "Source / note": "Limited services"
    },
    {
      "Date": "01-Oct-2026",
      "Day": "Thu",
      "Start time": "09:00",
      "End time": "09:45",
      "Origin / departure point": "Tioga Road",
      "Origin address": "",
      "Destination / activity": "Drive to Yosemite Valley",
      "Destination address": "Yosemite Valley",
      "Drive time": "~0h45",
      "Drive distance (mi)": "35",
      "Buffer / activity time": "45m",
      "Plan / key stops": "Park once if possible",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED IF OPEN",
      "Source / note": "NPS route timing"
    },
    {
      "Date": "01-Oct-2026",
      "Day": "Thu",
      "Start time": "09:45",
      "End time": "12:15",
      "Origin / departure point": "Yosemite Valley",
      "Origin address": "",
      "Destination / activity": "El Capitan + Valley + Village",
      "Destination address": "Yosemite Valley",
      "Drive time": "local",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "2h30",
      "Plan / key stops": "Short walks, no long hike",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Focus on highlights"
    },
    {
      "Date": "01-Oct-2026",
      "Day": "Thu",
      "Start time": "12:15",
      "End time": "12:45",
      "Origin / departure point": "Yosemite Valley",
      "Origin address": "",
      "Destination / activity": "Quick lunch",
      "Destination address": "Yosemite Village",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "30m",
      "Plan / key stops": "Packed lunch preferred",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Food buffer"
    },
    {
      "Date": "01-Oct-2026",
      "Day": "Thu",
      "Start time": "12:45",
      "End time": "14:15",
      "Origin / departure point": "Yosemite Valley",
      "Origin address": "",
      "Destination / activity": "Buffer + Tunnel View",
      "Destination address": "Tunnel View",
      "Drive time": "~0h15",
      "Drive distance (mi)": "8",
      "Buffer / activity time": "1h30",
      "Plan / key stops": "Tunnel View mandatory; cut buffer first if late",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "BUFFER",
      "Source / note": "Protect Burbank arrival"
    },
    {
      "Date": "01-Oct-2026",
      "Day": "Thu",
      "Start time": "14:15",
      "End time": "20:45",
      "Origin / departure point": "Yosemite",
      "Origin address": "",
      "Destination / activity": "Drive to Coast Burbank",
      "Destination address": "2011 W Olive Ave, Burbank",
      "Drive time": "~6h+",
      "Drive distance (mi)": "313",
      "Buffer / activity time": "6h30",
      "Plan / key stops": "Hwy 41; dinner/fuel en route",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "CAUTION",
      "Source / note": "LA traffic can add time"
    },
    {
      "Date": "01-Oct-2026",
      "Day": "Thu",
      "Start time": "20:45",
      "End time": "21:15",
      "Origin / departure point": "Coast Burbank",
      "Origin address": "",
      "Destination / activity": "Check-in + sleep",
      "Destination address": "2011 W Olive Ave",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "30m",
      "Plan / key stops": "Sleep; no late activity",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "Confirmation 1102922474"
    },
    {
      "Date": "02-Oct-2026",
      "Day": "Fri",
      "Start time": "08:30",
      "End time": "10:00",
      "Origin / departure point": "Coast Burbank",
      "Origin address": "",
      "Destination / activity": "Breakfast + transfer/security to Universal",
      "Destination address": "100 Universal City Plaza",
      "Drive time": "~0h15–0h25",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "1h30",
      "Plan / key stops": "Leave hotel early; target 10:00 opening",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "VERIFY HOURS",
      "Source / note": "Current published calendar 10:00–18:00; official hours vary"
    },
    {
      "Date": "02-Oct-2026",
      "Day": "Fri",
      "Start time": "10:00",
      "End time": "12:30",
      "Origin / departure point": "Universal",
      "Origin address": "",
      "Destination / activity": "Harry Potter + Studio Tour + key rides",
      "Destination address": "Universal Studios Hollywood",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "2h30",
      "Plan / key stops": "Start high-demand attractions first Ticket already purchased/confirmed.",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "Date-specific ticket required"
    },
    {
      "Date": "02-Oct-2026",
      "Day": "Fri",
      "Start time": "12:30",
      "End time": "13:15",
      "Origin / departure point": "Universal",
      "Origin address": "",
      "Destination / activity": "Lunch inside park",
      "Destination address": "Universal Studios Hollywood",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "45m",
      "Plan / key stops": "Eat inside the park; avoid leaving the security zone",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Operational"
    },
    {
      "Date": "02-Oct-2026",
      "Day": "Fri",
      "Start time": "13:15",
      "End time": "18:00",
      "Origin / departure point": "Universal",
      "Origin address": "",
      "Destination / activity": "Second park block",
      "Destination address": "Universal Studios Hollywood",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "4h45",
      "Plan / key stops": "Use live waits; finish core attractions by close",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Provisional close 18:00; verify official"
    },
    {
      "Date": "02-Oct-2026",
      "Day": "Fri",
      "Start time": "18:00",
      "End time": "19:15",
      "Origin / departure point": "Universal CityWalk",
      "Origin address": "",
      "Destination / activity": "Early dinner + return to hotel",
      "Destination address": "Coast Burbank",
      "Drive time": "~0h15–0h25",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "1h15",
      "Plan / key stops": "Skip HHN baseline; early sleep before Las Vegas drive",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "HHN separate ticket; baseline plan skips it"
    },
    {
      "Date": "03-Oct-2026",
      "Day": "Sat",
      "Start time": "09:00",
      "End time": "11:00",
      "Origin / departure point": "Coast Burbank Hotel",
      "Origin address": "2011 W Olive Ave, Burbank, CA",
      "Destination / activity": "Breakfast + check-out",
      "Destination address": "Burbank / Los Angeles, CA",
      "Drive time": "0",
      "Drive distance (mi)": 0,
      "Buffer / activity time": "2h",
      "Plan / key stops": "Check out by 11:00; luggage in car.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Coast Burbank booked 1→3 Oct."
    },
    {
      "Date": "03-Oct-2026",
      "Day": "Sat",
      "Start time": "11:15",
      "End time": "12:30",
      "Origin / departure point": "Burbank",
      "Origin address": "",
      "Destination / activity": "Griffith Observatory / Hollywood Sign views",
      "Destination address": "2800 E Observatory Rd, Los Angeles, CA 90027",
      "Drive time": "~0h20",
      "Drive distance (mi)": 0,
      "Buffer / activity time": "1h15",
      "Plan / key stops": "Light final-day activity; no strenuous hike.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "RECOMMENDED",
      "Source / note": "Keep flexible."
    },
    {
      "Date": "03-Oct-2026",
      "Day": "Sat",
      "Start time": "13:00",
      "End time": "14:30",
      "Origin / departure point": "Griffith Observatory",
      "Origin address": "2800 E Observatory Rd, Los Angeles, CA 90027",
      "Destination / activity": "Beverly Hills / Rodeo Drive",
      "Destination address": "Rodeo Drive, Beverly Hills, CA",
      "Drive time": "~0h35",
      "Drive distance (mi)": 17,
      "Buffer / activity time": "1h30",
      "Plan / key stops": "Lunch + photos/shopping. Skip if traffic is heavy.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "OPTIONAL",
      "Source / note": "User trip plan."
    },
    {
      "Date": "03-Oct-2026",
      "Day": "Sat",
      "Start time": "14:45",
      "End time": "16:15",
      "Origin / departure point": "Beverly Hills",
      "Origin address": "Rodeo Drive, Beverly Hills, CA",
      "Destination / activity": "Santa Monica / short beach stop",
      "Destination address": "Santa Monica Pier, Santa Monica, CA",
      "Drive time": "~0h30",
      "Drive distance (mi)": 11,
      "Buffer / activity time": "1h30",
      "Plan / key stops": "Optional; leave enough margin for airport drop-off.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "OPTIONAL",
      "Source / note": "Do not risk airport timing."
    },
    {
      "Date": "03-Oct-2026",
      "Day": "Sat",
      "Start time": "16:15",
      "End time": "19:00",
      "Origin / departure point": "Santa Monica / Los Angeles",
      "Origin address": "Santa Monica, CA",
      "Destination / activity": "Early dinner + drive to LAX / son airport drop-off",
      "Destination address": "Tom Bradley International Terminal, LAX, CA",
      "Drive time": "~0h45–1h00+",
      "Drive distance (mi)": 16,
      "Buffer / activity time": "2h45+",
      "Plan / key stops": "Target terminal around 19:00; UMNR/check-in documents.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Omer flies 3-Oct 23:00."
    },
    {
      "Date": "03-Oct-2026",
      "Day": "Sat",
      "Start time": "19:00",
      "End time": "23:00",
      "Origin / departure point": "LAX Terminal B",
      "Origin address": "Tom Bradley International Terminal, LAX, CA",
      "Destination / activity": "EL AL LY106 to TLV",
      "Destination address": "Tom Bradley International Terminal, LAX, CA",
      "Drive time": "0",
      "Drive distance (mi)": 0,
      "Buffer / activity time": "4h",
      "Plan / key stops": "UMNR desk/check-in/documents; remain until airline confirms child boarded.",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Omer flight."
    },
    {
      "Date": "03-Oct-2026",
      "Day": "Sat",
      "Start time": "23:30",
      "End time": "04:00",
      "Origin / departure point": "LAX / Tom Bradley",
      "Origin address": "LAX, CA",
      "Destination / activity": "Father: transfer to Studio 6 Suites LAX + check-in",
      "Destination address": "5101 West Century Boulevard, Los Angeles, CA 90045",
      "Drive time": "~0h10–0h20",
      "Drive distance (mi)": 3,
      "Buffer / activity time": "4h30",
      "Plan / key stops": "After Omer boards, transfer to booked LAX hotel and sleep.",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "Studio 6 Suites LAX; Booking ID 1056218566."
    },
    {
      "Date": "04-Oct-2026",
      "Day": "Sun",
      "Start time": "06:30",
      "End time": "11:30",
      "Origin / departure point": "Studio 6 Suites LAX",
      "Origin address": "5101 West Century Boulevard, Los Angeles, CA 90045",
      "Destination / activity": "Drive LAX → Las Vegas",
      "Destination address": "Las Vegas, NV",
      "Drive time": "~4h15–4h45",
      "Drive distance (mi)": 270,
      "Buffer / activity time": "5h",
      "Plan / key stops": "Early departure; fuel/comfort stop; allow Sunday traffic buffer.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Rental car remains with father through 04-Oct 14:00 return."
    },
    {
      "Date": "04-Oct-2026",
      "Day": "Sun",
      "Start time": "12:30",
      "End time": "14:00",
      "Origin / departure point": "Las Vegas, NV",
      "Origin address": "",
      "Destination / activity": "Rental car return - LAS",
      "Destination address": "Harry Reid International Airport Rental Car Center, Las Vegas, NV",
      "Drive time": "~0h20",
      "Drive distance (mi)": 10,
      "Buffer / activity time": "1h30",
      "Plan / key stops": "Fuel/return vehicle; final inspection; airport after return.",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "User booking: pickup 24-Sep 09:00, return 04-Oct 14:00."
    },
    {
      "Date": "17-Sep-2026",
      "Day": "Thu",
      "Start time": "18:00",
      "End time": "19:45",
      "Origin / departure point": "EWR",
      "Origin address": "",
      "Destination / activity": "Arrive EWR, Uber to hotel, check-in",
      "Destination address": "150 W 48th St, New York, NY 10036",
      "Drive time": "Uber / taxi from airport",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Direct transfer after arrival; keep it easy after the flight.",
      "Booking required?": "No",
      "Planned direct cost ($)": 85,
      "Status / action": "LOCKED",
      "Source / note": "Uber estimate"
    },
    {
      "Date": "17-Sep-2026",
      "Day": "Thu",
      "Start time": "21:00",
      "End time": "22:15",
      "Origin / departure point": "Hotel",
      "Origin address": "",
      "Destination / activity": "Times Square stroll + first-night lights",
      "Destination address": "Times Square, New York, NY 10036",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Stay around 44th–48th St. Avoid over-planning.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "17-Sep-2026",
      "Day": "Thu",
      "Start time": "22:15",
      "End time": "23:00",
      "Origin / departure point": "Times Square",
      "Origin address": "",
      "Destination / activity": "Dinner: Joe's Pizza or Junior's",
      "Destination address": "Times Square, New York, NY 10036",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Classic easy first-night meal; low effort, high payoff.",
      "Booking required?": "No",
      "Planned direct cost ($)": 40,
      "Status / action": "LOCKED",
      "Source / note": "Pizza / dessert"
    },
    {
      "Date": "18-Sep-2026",
      "Day": "Fri",
      "Start time": "08:30",
      "End time": "09:00",
      "Origin / departure point": "Hotel",
      "Origin address": "",
      "Destination / activity": "Breakfast near hotel",
      "Destination address": "Nearby breakfast, New York, NY",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Keep it simple before the long day.",
      "Booking required?": "No",
      "Planned direct cost ($)": 30,
      "Status / action": "LOCKED",
      "Source / note": "Breakfast"
    },
    {
      "Date": "18-Sep-2026",
      "Day": "Fri",
      "Start time": "09:15",
      "End time": "10:00",
      "Origin / departure point": "Breakfast",
      "Origin address": "",
      "Destination / activity": "Grand Central Terminal + Whispering Gallery",
      "Destination address": "89 E 42nd St, New York, NY 10017",
      "Drive time": "Subway or walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Best first stop for wow-factor without rush.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "18-Sep-2026",
      "Day": "Fri",
      "Start time": "10:00",
      "End time": "11:00",
      "Origin / departure point": "Grand Central",
      "Origin address": "",
      "Destination / activity": "Bryant Park + New York Public Library exterior",
      "Destination address": "Bryant Park, New York, NY 10018",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Beautiful and calm; good reset between landmarks.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "18-Sep-2026",
      "Day": "Fri",
      "Start time": "11:15",
      "End time": "12:45",
      "Origin / departure point": "Bryant Park",
      "Origin address": "",
      "Destination / activity": "SUMMIT One Vanderbilt timed entry",
      "Destination address": "45 E 42nd St, New York, NY 10017",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Strongly book ahead. Best view for this itinerary.",
      "Booking required?": "Yes",
      "Planned direct cost ($)": 95,
      "Status / action": "BOOK AHEAD",
      "Source / note": "Timed ticket"
    },
    {
      "Date": "18-Sep-2026",
      "Day": "Fri",
      "Start time": "13:00",
      "End time": "13:45",
      "Origin / departure point": "One Vanderbilt",
      "Origin address": "",
      "Destination / activity": "Lunch: Los Tacos No.1",
      "Destination address": "229 W 43rd St, New York, NY 10036",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Fast, good, and works well for both ages.",
      "Booking required?": "No",
      "Planned direct cost ($)": 42,
      "Status / action": "LOCKED",
      "Source / note": "Lunch"
    },
    {
      "Date": "18-Sep-2026",
      "Day": "Fri",
      "Start time": "14:00",
      "End time": "15:15",
      "Origin / departure point": "Lunch stop",
      "Origin address": "",
      "Destination / activity": "Fifth Avenue / LEGO / Nintendo / St. Patrick’s Cathedral",
      "Destination address": "Fifth Avenue, New York, NY",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "This is the “fun city” section for the 14-year-old.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "18-Sep-2026",
      "Day": "Fri",
      "Start time": "15:30",
      "End time": "17:45",
      "Origin / departure point": "Fifth Ave",
      "Origin address": "",
      "Destination / activity": "Central Park: Bethesda Terrace, Bow Bridge, The Lake",
      "Destination address": "Central Park South, New York, NY 10019",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Best walking section of the trip; keep a relaxed pace.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "18-Sep-2026",
      "Day": "Fri",
      "Start time": "19:00",
      "End time": "20:30",
      "Origin / departure point": "Central Park",
      "Origin address": "",
      "Destination / activity": "Dinner: Burger Joint or similar casual spot",
      "Destination address": "Midtown Manhattan, New York, NY",
      "Drive time": "Subway / walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Good before an evening view.",
      "Booking required?": "No",
      "Planned direct cost ($)": 55,
      "Status / action": "LOCKED",
      "Source / note": "Dinner"
    },
    {
      "Date": "18-Sep-2026",
      "Day": "Fri",
      "Start time": "21:00",
      "End time": "22:15",
      "Origin / departure point": "Dinner",
      "Origin address": "",
      "Destination / activity": "Top of the Rock evening slot",
      "Destination address": "45 Rockefeller Plaza, New York, NY 10111",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Book ahead. Night skyline is the point here.",
      "Booking required?": "Yes",
      "Planned direct cost ($)": 82,
      "Status / action": "BOOK AHEAD",
      "Source / note": "Timed ticket"
    },
    {
      "Date": "19-Sep-2026",
      "Day": "Sat",
      "Start time": "08:30",
      "End time": "09:15",
      "Origin / departure point": "Hotel",
      "Origin address": "",
      "Destination / activity": "Breakfast + subway to downtown",
      "Destination address": "Battery Park, New York, NY 10004",
      "Drive time": "Subway",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Saturday should start early to keep the day smooth.",
      "Booking required?": "No",
      "Planned direct cost ($)": 28,
      "Status / action": "LOCKED",
      "Source / note": "Breakfast"
    },
    {
      "Date": "19-Sep-2026",
      "Day": "Sat",
      "Start time": "09:30",
      "End time": "10:15",
      "Origin / departure point": "Battery Park",
      "Origin address": "",
      "Destination / activity": "Battery Park + Staten Island Ferry round trip",
      "Destination address": "4 South St, New York, NY 10004",
      "Drive time": "Walk + ferry",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Excellent value and a great harbor view.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Free ferry"
    },
    {
      "Date": "19-Sep-2026",
      "Day": "Sat",
      "Start time": "10:30",
      "End time": "11:30",
      "Origin / departure point": "Ferry",
      "Origin address": "",
      "Destination / activity": "Wall Street / Charging Bull / NYSE exterior",
      "Destination address": "Wall Street, New York, NY 10005",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Compact, efficient downtown loop.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "19-Sep-2026",
      "Day": "Sat",
      "Start time": "11:45",
      "End time": "12:45",
      "Origin / departure point": "Wall Street",
      "Origin address": "",
      "Destination / activity": "9/11 Memorial",
      "Destination address": "180 Greenwich St, New York, NY 10007",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Emotional but important stop; keep it respectful.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "19-Sep-2026",
      "Day": "Sat",
      "Start time": "13:00",
      "End time": "14:00",
      "Origin / departure point": "9/11 Memorial",
      "Origin address": "",
      "Destination / activity": "Lunch: Eataly Downtown / nearby",
      "Destination address": "World Trade Center, New York, NY 10007",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Easy lunch before SoHo.",
      "Booking required?": "No",
      "Planned direct cost ($)": 60,
      "Status / action": "LOCKED",
      "Source / note": "Lunch"
    },
    {
      "Date": "19-Sep-2026",
      "Day": "Sat",
      "Start time": "14:15",
      "End time": "16:00",
      "Origin / departure point": "Downtown",
      "Origin address": "",
      "Destination / activity": "SoHo / Prince / Spring / Greene Streets",
      "Destination address": "SoHo, New York, NY",
      "Drive time": "Subway or walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Best for shopping, architecture and atmosphere.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "19-Sep-2026",
      "Day": "Sat",
      "Start time": "16:15",
      "End time": "17:00",
      "Origin / departure point": "SoHo",
      "Origin address": "",
      "Destination / activity": "Little Italy + dessert stop",
      "Destination address": "Little Italy, New York, NY",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Short and sweet; don’t overdo it.",
      "Booking required?": "No",
      "Planned direct cost ($)": 20,
      "Status / action": "LOCKED",
      "Source / note": "Dessert"
    },
    {
      "Date": "19-Sep-2026",
      "Day": "Sat",
      "Start time": "17:15",
      "End time": "18:30",
      "Origin / departure point": "Little Italy",
      "Origin address": "",
      "Destination / activity": "Walk toward Brooklyn Bridge / skyline photos",
      "Destination address": "Brooklyn Bridge, New York, NY",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Start before sunset to get the best light.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "19-Sep-2026",
      "Day": "Sat",
      "Start time": "18:30",
      "End time": "20:00",
      "Origin / departure point": "Brooklyn Bridge entrance",
      "Origin address": "",
      "Destination / activity": "Brooklyn Bridge crossing",
      "Destination address": "DUMBO, Brooklyn, NY 11201",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "One of the most memorable parts of the whole trip.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "19-Sep-2026",
      "Day": "Sat",
      "Start time": "20:00",
      "End time": "21:15",
      "Origin / departure point": "Brooklyn Bridge",
      "Origin address": "",
      "Destination / activity": "DUMBO + Washington Street + waterfront",
      "Destination address": "DUMBO, Brooklyn, NY 11201",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Best place for skyline photos and a calm finish.",
      "Booking required?": "No",
      "Planned direct cost ($)": 25,
      "Status / action": "LOCKED",
      "Source / note": "Snack / ice cream"
    },
    {
      "Date": "19-Sep-2026",
      "Day": "Sat",
      "Start time": "21:15",
      "End time": "22:00",
      "Origin / departure point": "DUMBO",
      "Origin address": "",
      "Destination / activity": "Optional: Juliana's Pizza",
      "Destination address": "19 Old Fulton St, Brooklyn, NY 11201",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Great if you still have appetite after the day.",
      "Booking required?": "No",
      "Planned direct cost ($)": 50,
      "Status / action": "OPTIONAL",
      "Source / note": "Dinner"
    },
    {
      "Date": "20-Sep-2026",
      "Day": "Sun",
      "Start time": "09:00",
      "End time": "09:40",
      "Origin / departure point": "Hotel",
      "Origin address": "",
      "Destination / activity": "Breakfast + subway to High Line",
      "Destination address": "Gansevoort St & Washington St, New York, NY 10014",
      "Drive time": "Subway",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Gentle morning before the long walking stretch.",
      "Booking required?": "No",
      "Planned direct cost ($)": 25,
      "Status / action": "LOCKED",
      "Source / note": "Breakfast"
    },
    {
      "Date": "20-Sep-2026",
      "Day": "Sun",
      "Start time": "10:00",
      "End time": "11:15",
      "Origin / departure point": "High Line",
      "Origin address": "",
      "Destination / activity": "High Line south to north",
      "Destination address": "The High Line, New York, NY",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Best enjoyed on foot; one of NYC’s signature walks.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "20-Sep-2026",
      "Day": "Sun",
      "Start time": "10:45",
      "End time": "16:30",
      "Origin / departure point": "Hudson Yards",
      "Origin address": "",
      "Destination / activity": "OPTIONAL: New York Jets vs Green Bay Packers (MetLife Stadium)",
      "Destination address": "1 MetLife Stadium Dr, East Rutherford, NJ 07073",
      "Drive time": "Subway/NJ Transit + shuttle or rideshare",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "If chosen, this becomes the main event of the day. Must book ahead.",
      "Booking required?": "Yes",
      "Planned direct cost ($)": 220,
      "Status / action": "BOOK AHEAD",
      "Source / note": "Game ticket"
    },
    {
      "Date": "20-Sep-2026",
      "Day": "Sun",
      "Start time": "11:15",
      "End time": "12:15",
      "Origin / departure point": "High Line",
      "Origin address": "",
      "Destination / activity": "Chelsea Market",
      "Destination address": "75 9th Ave, New York, NY 10011",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Excellent stop for food and atmosphere.",
      "Booking required?": "No",
      "Planned direct cost ($)": 30,
      "Status / action": "LOCKED",
      "Source / note": "Snack / lunch option"
    },
    {
      "Date": "20-Sep-2026",
      "Day": "Sun",
      "Start time": "12:20",
      "End time": "13:00",
      "Origin / departure point": "Chelsea Market",
      "Origin address": "",
      "Destination / activity": "Little Island + Hudson River Park",
      "Destination address": "Pier 55, W 13th St, New York, NY 10014",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "A calm, magical place that many tourists skip.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "20-Sep-2026",
      "Day": "Sun",
      "Start time": "13:15",
      "End time": "14:00",
      "Origin / departure point": "Little Island",
      "Origin address": "",
      "Destination / activity": "Lunch: Miznon / Los Mariscos / similar",
      "Destination address": "20 Hudson Yards, New York, NY 10001",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Pick one based on mood and appetite.",
      "Booking required?": "No",
      "Planned direct cost ($)": 45,
      "Status / action": "LOCKED",
      "Source / note": "Lunch"
    },
    {
      "Date": "20-Sep-2026",
      "Day": "Sun",
      "Start time": "14:15",
      "End time": "15:15",
      "Origin / departure point": "Lunch stop",
      "Origin address": "",
      "Destination / activity": "Hudson Yards / Vessel exterior / shopping",
      "Destination address": "20 Hudson Yards, New York, NY 10001",
      "Drive time": "Walk",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Good if you want one more Manhattan landmark.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": ""
    },
    {
      "Date": "20-Sep-2026",
      "Day": "Sun",
      "Start time": "19:45",
      "End time": "21:00",
      "Origin / departure point": "Hudson Yards",
      "Origin address": "",
      "Destination / activity": "Dinner back in Manhattan (if no game)",
      "Destination address": "Midtown Manhattan, New York, NY",
      "Drive time": "Subway / rideshare",
      "Drive distance (mi)": "",
      "Buffer / activity time": "",
      "Plan / key stops": "Use this if you skip the NFL game.",
      "Booking required?": "No",
      "Planned direct cost ($)": 60,
      "Status / action": "LOCKED",
      "Source / note": "Dinner"
    },
    {
      "Date": "21-Sep-2026",
      "Day": "Mon",
      "Start time": "12:00",
      "End time": "13:00",
      "Origin / departure point": "NYC hotel",
      "Origin address": "",
      "Destination / activity": "Lunch + final packing",
      "Destination address": "NYC",
      "Drive time": "—",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "1h",
      "Plan / key stops": "Eat, finish packing and keep the day light",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "NYC itinerary"
    },
    {
      "Date": "21-Sep-2026",
      "Day": "Mon",
      "Start time": "13:00",
      "End time": "15:00",
      "Origin / departure point": "NYC hotel",
      "Origin address": "",
      "Destination / activity": "Final shopping / rest",
      "Destination address": "Midtown / hotel",
      "Drive time": "—",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "2h",
      "Plan / key stops": "Only one relaxed outing; return to hotel by 15:00",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "OPTIONAL",
      "Source / note": "User request: start from midday"
    },
    {
      "Date": "21-Sep-2026",
      "Day": "Mon",
      "Start time": "15:00",
      "End time": "17:30",
      "Origin / departure point": "NYC hotel",
      "Origin address": "",
      "Destination / activity": "Shower, luggage, final hotel buffer",
      "Destination address": "NYC hotel",
      "Drive time": "—",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "2h30",
      "Plan / key stops": "Be fully packed and ready; do not add another attraction",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Protect JFK buffer"
    },
    {
      "Date": "21-Sep-2026",
      "Day": "Mon",
      "Start time": "18:00",
      "End time": "19:30",
      "Origin / departure point": "NYC hotel",
      "Origin address": "",
      "Destination / activity": "Transfer + JFK check-in",
      "Destination address": "JFK Airport",
      "Drive time": "~1h00–1h30",
      "Drive distance (mi)": "15",
      "Buffer / activity time": "1h30",
      "Plan / key stops": "Leave large NYC traffic buffer",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "NYC itinerary; exact flight/ticket verify"
    },
    {
      "Date": "21-Sep-2026",
      "Day": "Mon",
      "Start time": "21:39",
      "End time": "~01:00",
      "Origin / departure point": "JFK",
      "Origin address": "",
      "Destination / activity": "Flight to Las Vegas",
      "Destination address": "LAS",
      "Drive time": "~5h50",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "Flight",
      "Plan / key stops": "JetBlue per trip details; verify exact arrival time",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "TICKET VERIFY",
      "Source / note": "User trip details"
    },
    {
      "Date": "22-Sep-2026",
      "Day": "Tue",
      "Start time": "01:15",
      "End time": "01:45",
      "Origin / departure point": "LAS",
      "Origin address": "",
      "Destination / activity": "Transfer + Palazzo check-in",
      "Destination address": "The Palazzo at The Venetian Resort",
      "Drive time": "~0h20",
      "Drive distance (mi)": "8",
      "Buffer / activity time": "30m",
      "Plan / key stops": "Check in and sleep",
      "Booking required?": "Hotel booked",
      "Planned direct cost ($)": 0,
      "Status / action": "USER-CONFIRMED",
      "Source / note": "User-confirmed hotel; confirmation absent from current workbook"
    },
    {
      "Date": "22-Sep-2026",
      "Day": "Tue",
      "Start time": "09:00",
      "End time": "10:15",
      "Origin / departure point": "Palazzo",
      "Origin address": "",
      "Destination / activity": "Wake + breakfast at Grand Lux",
      "Destination address": "Venetian area",
      "Drive time": "walk",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "1h15",
      "Plan / key stops": "Slow first morning",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "grandluxcafe.com"
    },
    {
      "Date": "22-Sep-2026",
      "Day": "Tue",
      "Start time": "10:15",
      "End time": "11:40",
      "Origin / departure point": "Venetian",
      "Origin address": "",
      "Destination / activity": "Venetian canals + Wynn",
      "Destination address": "3355 S Las Vegas Blvd / Wynn",
      "Drive time": "walk",
      "Drive distance (mi)": "1",
      "Buffer / activity time": "1h25",
      "Plan / key stops": "Canals, St Mark's, Wynn gardens",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Vegas itinerary"
    },
    {
      "Date": "22-Sep-2026",
      "Day": "Tue",
      "Start time": "12:30",
      "End time": "13:15",
      "Origin / departure point": "Palazzo",
      "Origin address": "",
      "Destination / activity": "Lunch",
      "Destination address": "Venetian / Palazzo",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "45m",
      "Plan / key stops": "Fast lunch",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Vegas itinerary"
    },
    {
      "Date": "22-Sep-2026",
      "Day": "Tue",
      "Start time": "13:30",
      "End time": "17:30",
      "Origin / departure point": "Palazzo",
      "Origin address": "",
      "Destination / activity": "Las Vegas North Premium Outlets",
      "Destination address": "875 S Grand Central Pkwy",
      "Drive time": "~0h10–0h20",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "4h",
      "Plan / key stops": "Samsonite, BOSS, Nike/adidas/On, Ralph/Lacoste",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "premiumoutlets.com"
    },
    {
      "Date": "22-Sep-2026",
      "Day": "Tue",
      "Start time": "17:45",
      "End time": "19:15",
      "Origin / departure point": "Palazzo",
      "Origin address": "",
      "Destination / activity": "Rest / pool / shower",
      "Destination address": "Palazzo",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "1h30",
      "Plan / key stops": "Real recovery buffer",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Vegas itinerary"
    },
    {
      "Date": "22-Sep-2026",
      "Day": "Tue",
      "Start time": "19:30",
      "End time": "23:00",
      "Origin / departure point": "Palazzo",
      "Origin address": "",
      "Destination / activity": "Dinner + Caesars/Bellagio",
      "Destination address": "Bellagio / Caesars",
      "Drive time": "~0h10–0h20",
      "Drive distance (mi)": "2",
      "Buffer / activity time": "3h30",
      "Plan / key stops": "Dinner then conservatory/fountains; back by 23:00",
      "Booking required?": "Optional",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Bellagio official site"
    },
    {
      "Date": "23-Sep-2026",
      "Day": "Wed",
      "Start time": "08:00",
      "End time": "09:00",
      "Origin / departure point": "Palazzo",
      "Origin address": "3325 S Las Vegas Blvd, Las Vegas, NV",
      "Destination / activity": "Dig This - interactive heavy-equipment experience (optional)",
      "Destination address": "3012 S Rancho Dr, Las Vegas, NV 89102",
      "Drive time": "~0h15",
      "Drive distance (mi)": 8,
      "Buffer / activity time": "1h",
      "Plan / key stops": "Short hands-on physical activity; optional and not booked. Return by Uber/Lyft.",
      "Booking required?": "YES",
      "Planned direct cost ($)": 56,
      "Status / action": "RECOMMENDED / NOT BOOKED",
      "Source / note": "Latest trip plan; 2 people at ~$28 pp."
    },
    {
      "Date": "23-Sep-2026",
      "Day": "Wed",
      "Start time": "09:00",
      "End time": "13:15",
      "Origin / departure point": "Dig This / Las Vegas",
      "Origin address": "3012 S Rancho Dr, Las Vegas, NV 89102",
      "Destination / activity": "Return, breakfast, rest + prepare for Sphere",
      "Destination address": "Palazzo / Venetian, Las Vegas, NV",
      "Drive time": "~0h15",
      "Drive distance (mi)": 8,
      "Buffer / activity time": "4h15",
      "Plan / key stops": "Return to hotel; breakfast; rest; leave for Sphere around 13:15.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "No rental car; Uber/Lyft."
    },
    {
      "Date": "23-Sep-2026",
      "Day": "Wed",
      "Start time": "13:15",
      "End time": "13:45",
      "Origin / departure point": "Palazzo",
      "Origin address": "3325 S Las Vegas Blvd, Las Vegas, NV",
      "Destination / activity": "Transfer to Sphere",
      "Destination address": "255 Sands Ave, Las Vegas, NV 89169",
      "Drive time": "~0h10–0h20",
      "Drive distance (mi)": 1,
      "Buffer / activity time": "30m",
      "Plan / key stops": "Arrive before doors.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Sphere Las Vegas."
    },
    {
      "Date": "23-Sep-2026",
      "Day": "Wed",
      "Start time": "14:00",
      "End time": "16:00",
      "Origin / departure point": "Sphere",
      "Origin address": "255 Sands Ave, Las Vegas, NV 89169",
      "Destination / activity": "The Wizard of Oz at Sphere",
      "Destination address": "Sphere Las Vegas, 255 Sands Ave, Las Vegas, NV 89169",
      "Drive time": "0",
      "Drive distance (mi)": 0,
      "Buffer / activity time": "2h",
      "Plan / key stops": "Confirmed 14:00 show; Section 406 Row 10.",
      "Booking required?": "YES",
      "Planned direct cost ($)": 185,
      "Status / action": "BOOKED",
      "Source / note": "User-confirmed ticket booking for 14:00."
    },
    {
      "Date": "23-Sep-2026",
      "Day": "Wed",
      "Start time": "16:00",
      "End time": "20:00",
      "Origin / departure point": "Sphere",
      "Origin address": "255 Sands Ave, Las Vegas, NV 89169",
      "Destination / activity": "Strip / dinner / free evening",
      "Destination address": "Las Vegas Strip, NV",
      "Drive time": "~0h15",
      "Drive distance (mi)": 5,
      "Buffer / activity time": "4h",
      "Plan / key stops": "Keep evening flexible after Sphere.",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "User trip plan."
    },
    {
      "Date": "24-Sep-2026",
      "Day": "Thu",
      "Start time": "09:00",
      "End time": "09:45",
      "Origin / departure point": "Palazzo",
      "Origin address": "",
      "Destination / activity": "Transfer + Alamo rental pickup",
      "Destination address": "7135 Gilespie St, Las Vegas",
      "Drive time": "~0h10–0h20",
      "Drive distance (mi)": 8,
      "Buffer / activity time": "45m",
      "Plan / key stops": "Inspect vehicle, photos, odometer, fuel",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "User booking: pickup 24-Sep 09:00; rental remains through 04-Oct 14:00."
    },
    {
      "Date": "24-Sep-2026",
      "Day": "Thu",
      "Start time": "09:45",
      "End time": "14:45",
      "Origin / departure point": "LAS Rent-A-Car Center",
      "Origin address": "",
      "Destination / activity": "Drive to Grand Canyon South Rim",
      "Destination address": "South Entrance AZ-64",
      "Drive time": "~4h45–5h00",
      "Drive distance (mi)": 278,
      "Buffer / activity time": "5h",
      "Plan / key stops": "One rest/fuel stop if needed",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Adjusted for 09:00 planned rental pickup."
    },
    {
      "Date": "24-Sep-2026",
      "Day": "Thu",
      "Start time": "14:45",
      "End time": "15:30",
      "Origin / departure point": "Grand Canyon",
      "Origin address": "",
      "Destination / activity": "Park entry + lunch",
      "Destination address": "Visitor Center / Mather",
      "Drive time": "~0h15",
      "Drive distance (mi)": 8,
      "Buffer / activity time": "45m",
      "Plan / key stops": "Enter, eat fast, start views",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Adjusted for rental pickup time."
    },
    {
      "Date": "24-Sep-2026",
      "Day": "Thu",
      "Start time": "15:30",
      "End time": "17:30",
      "Origin / departure point": "Mather",
      "Origin address": "",
      "Destination / activity": "Mather + Yavapai + Rim Trail",
      "Destination address": "South Rim",
      "Drive time": "local",
      "Drive distance (mi)": 8,
      "Buffer / activity time": "2h",
      "Plan / key stops": "2–3 key viewpoints",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Adjusted for rental pickup time."
    },
    {
      "Date": "24-Sep-2026",
      "Day": "Thu",
      "Start time": "17:45",
      "End time": "18:35",
      "Origin / departure point": "South Rim",
      "Origin address": "",
      "Destination / activity": "Sunset block",
      "Destination address": "Mather/Hopi area",
      "Drive time": "local",
      "Drive distance (mi)": 8,
      "Buffer / activity time": "50m",
      "Plan / key stops": "Sunset target around 18:22",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Adjusted for 09:00 pickup."
    },
    {
      "Date": "24-Sep-2026",
      "Day": "Thu",
      "Start time": "18:40",
      "End time": "19:30",
      "Origin / departure point": "Grand Canyon",
      "Origin address": "",
      "Destination / activity": "Drive to The Outpost Grand Canyon",
      "Destination address": "Valle AZ",
      "Drive time": "~0h40–0h50",
      "Drive distance (mi)": 28,
      "Buffer / activity time": "50m",
      "Plan / key stops": "Check in after sunset",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "Agoda 702603347"
    },
    {
      "Date": "25-Sep-2026",
      "Day": "Fri",
      "Start time": "05:45",
      "End time": "08:00",
      "Origin / departure point": "The Outpost",
      "Origin address": "",
      "Destination / activity": "Sunrise + breakfast + depart",
      "Destination address": "South Rim",
      "Drive time": "~0h25–0h35",
      "Drive distance (mi)": "25",
      "Buffer / activity time": "2h15",
      "Plan / key stops": "Sunrise then short rim walk; breakfast",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Sunrise around 06:18; recheck"
    },
    {
      "Date": "25-Sep-2026",
      "Day": "Fri",
      "Start time": "08:00",
      "End time": "09:30",
      "Origin / departure point": "Grand Canyon",
      "Origin address": "",
      "Destination / activity": "Desert View Drive",
      "Destination address": "Desert View Watchtower",
      "Drive time": "~1h30",
      "Drive distance (mi)": "25",
      "Buffer / activity time": "1h30",
      "Plan / key stops": "One or two viewpoints",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "RECOMMENDED",
      "Source / note": "NPS"
    },
    {
      "Date": "25-Sep-2026",
      "Day": "Fri",
      "Start time": "09:30",
      "End time": "12:15",
      "Origin / departure point": "Desert View",
      "Origin address": "",
      "Destination / activity": "Drive to Page",
      "Destination address": "Home2 Suites Page",
      "Drive time": "~2h43",
      "Drive distance (mi)": "138",
      "Buffer / activity time": "2h45",
      "Plan / key stops": "Fuel/coffee if needed",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Route estimate"
    },
    {
      "Date": "25-Sep-2026",
      "Day": "Fri",
      "Start time": "12:15",
      "End time": "13:15",
      "Origin / departure point": "Home2 Page",
      "Origin address": "",
      "Destination / activity": "Lunch + luggage drop",
      "Destination address": "681 Scenic View Rd",
      "Drive time": "0h05",
      "Drive distance (mi)": "2",
      "Buffer / activity time": "1h",
      "Plan / key stops": "Room check-in is later; leave bags if needed",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "Hotel check-in 15:00"
    },
    {
      "Date": "25-Sep-2026",
      "Day": "Fri",
      "Start time": "15:45",
      "End time": "17:30",
      "Origin / departure point": "Page",
      "Origin address": "",
      "Destination / activity": "Horseshoe Bend",
      "Destination address": "US-89 MM 545",
      "Drive time": "0h10",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "1h45",
      "Plan / key stops": "0.6 mi each way",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Page attraction"
    },
    {
      "Date": "25-Sep-2026",
      "Day": "Fri",
      "Start time": "18:00",
      "End time": "19:15",
      "Origin / departure point": "Page",
      "Origin address": "",
      "Destination / activity": "Dinner + easy evening",
      "Destination address": "Page",
      "Drive time": "0h10",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "1h15",
      "Plan / key stops": "Pack for kayak",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Flexible"
    },
    {
      "Date": "26-Sep-2026",
      "Day": "Sat",
      "Start time": "07:45",
      "End time": "08:30",
      "Origin / departure point": "Home2 Page",
      "Origin address": "",
      "Destination / activity": "Breakfast + gear",
      "Destination address": "Home2 Page",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "45m",
      "Plan / key stops": "Water shoes, sunscreen, dry clothes",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Hotel breakfast"
    },
    {
      "Date": "26-Sep-2026",
      "Day": "Sat",
      "Start time": "08:30",
      "End time": "09:00",
      "Origin / departure point": "Home2 Page",
      "Origin address": "",
      "Destination / activity": "Drive to kayak launch",
      "Destination address": "910 Coppermine Rd",
      "Drive time": "~0h15",
      "Drive distance (mi)": "7",
      "Buffer / activity time": "30m",
      "Plan / key stops": "Arrive early",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "CONFIRMED",
      "Source / note": "Operator confirmed"
    },
    {
      "Date": "26-Sep-2026",
      "Day": "Sat",
      "Start time": "09:30",
      "End time": "12:00",
      "Origin / departure point": "Kayak",
      "Origin address": "",
      "Destination / activity": "Guided Lake Powell kayak",
      "Destination address": "Lake Powell",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "2h30",
      "Plan / key stops": "Double kayak + gear/dry bags",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "CONFIRMED",
      "Source / note": "Confirmed"
    },
    {
      "Date": "26-Sep-2026",
      "Day": "Sat",
      "Start time": "12:15",
      "End time": "15:15",
      "Origin / departure point": "Page",
      "Origin address": "",
      "Destination / activity": "Lunch + rest + change",
      "Destination address": "Page",
      "Drive time": "0h10",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "3h",
      "Plan / key stops": "No sightseeing",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Recovery buffer"
    },
    {
      "Date": "26-Sep-2026",
      "Day": "Sat",
      "Start time": "15:30",
      "End time": "17:40",
      "Origin / departure point": "Page",
      "Origin address": "",
      "Destination / activity": "Upper Antelope Canyon",
      "Destination address": "22 S Lake Powell Blvd",
      "Drive time": "0h10",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "2h10",
      "Plan / key stops": "Arrive 15:30 for 16:00 tour",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "CONFIRMED",
      "Source / note": "Confirmed"
    },
    {
      "Date": "26-Sep-2026",
      "Day": "Sat",
      "Start time": "18:00",
      "End time": "19:15",
      "Origin / departure point": "Page",
      "Origin address": "",
      "Destination / activity": "Dinner",
      "Destination address": "Page",
      "Drive time": "0h10",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "1h15",
      "Plan / key stops": "Early dinner",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Flexible"
    },
    {
      "Date": "27-Sep-2026",
      "Day": "Sun",
      "Start time": "07:15",
      "End time": "08:00",
      "Origin / departure point": "Home2 Page",
      "Origin address": "",
      "Destination / activity": "Breakfast + checkout",
      "Destination address": "681 Scenic View Rd",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "45m",
      "Plan / key stops": "Leave with water/layers",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Hotel breakfast"
    },
    {
      "Date": "27-Sep-2026",
      "Day": "Sun",
      "Start time": "08:00",
      "End time": "10:45",
      "Origin / departure point": "Page",
      "Origin address": "",
      "Destination / activity": "Drive to Bryce",
      "Destination address": "Bryce Canyon Shuttle Station",
      "Drive time": "~2h30–2h45",
      "Drive distance (mi)": "150",
      "Buffer / activity time": "2h45",
      "Plan / key stops": "Utah +1h vs Page",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Time-zone shift"
    },
    {
      "Date": "27-Sep-2026",
      "Day": "Sun",
      "Start time": "10:45",
      "End time": "11:10",
      "Origin / departure point": "Bryce route",
      "Origin address": "",
      "Destination / activity": "Optional Red Canyon",
      "Destination address": "Red Canyon Visitor Center",
      "Drive time": "~0h15",
      "Drive distance (mi)": "10",
      "Buffer / activity time": "25m",
      "Plan / key stops": "Only if on time",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "OPTIONAL",
      "Source / note": "Skip if late"
    },
    {
      "Date": "27-Sep-2026",
      "Day": "Sun",
      "Start time": "11:15",
      "End time": "12:15",
      "Origin / departure point": "Bryce",
      "Origin address": "",
      "Destination / activity": "Lunch",
      "Destination address": "Bryce Canyon City",
      "Drive time": "local",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "1h",
      "Plan / key stops": "Light meal before hike",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Food nearby"
    },
    {
      "Date": "27-Sep-2026",
      "Day": "Sun",
      "Start time": "12:30",
      "End time": "13:00",
      "Origin / departure point": "Bryce",
      "Origin address": "",
      "Destination / activity": "Park entry + setup",
      "Destination address": "Sunset Point",
      "Drive time": "~0h10",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "30m",
      "Plan / key stops": "Use pass; no timed entry",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Private car; no late shuttle dependency"
    },
    {
      "Date": "27-Sep-2026",
      "Day": "Sun",
      "Start time": "13:00",
      "End time": "16:45",
      "Origin / departure point": "Sunset Point",
      "Origin address": "",
      "Destination / activity": "Navajo + Peekaboo Combination Loop",
      "Destination address": "Bryce Amphitheater",
      "Drive time": "local",
      "Drive distance (mi)": "2",
      "Buffer / activity time": "3h45",
      "Plan / key stops": "Strenuous; ~7.9 km; check conditions",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "NPS trail / shuttle verified"
    },
    {
      "Date": "27-Sep-2026",
      "Day": "Sun",
      "Start time": "17:00",
      "End time": "18:30",
      "Origin / departure point": "Bryce",
      "Origin address": "",
      "Destination / activity": "Drive to Cedar City hotel",
      "Destination address": "50 W 200 N Cedar City",
      "Drive time": "~1h30",
      "Drive distance (mi)": "80",
      "Buffer / activity time": "1h30",
      "Plan / key stops": "Dinner/check-in",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "Booked 27→28"
    },
    {
      "Date": "28-Sep-2026",
      "Day": "Mon",
      "Start time": "07:30",
      "End time": "10:00",
      "Origin / departure point": "Cedar City hotel",
      "Origin address": "",
      "Destination / activity": "Breakfast + easy morning",
      "Destination address": "Cedar City",
      "Drive time": "local",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "2h30",
      "Plan / key stops": "Fuel/groceries; no strenuous activity",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Hotel breakfast"
    },
    {
      "Date": "28-Sep-2026",
      "Day": "Mon",
      "Start time": "10:30",
      "End time": "15:00",
      "Origin / departure point": "Cedar City",
      "Origin address": "",
      "Destination / activity": "Drive toward Beryl + lunch + Outpost arrival",
      "Destination address": "Beryl / Outpost X",
      "Drive time": "~1h30 + buffer",
      "Drive distance (mi)": "65",
      "Buffer / activity time": "4h30",
      "Plan / key stops": "Lunch on route; arrive before 15:00 check-in",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "Use exact booking pin"
    },
    {
      "Date": "28-Sep-2026",
      "Day": "Mon",
      "Start time": "15:00",
      "End time": "20:30",
      "Origin / departure point": "Outpost X",
      "Origin address": "",
      "Destination / activity": "Glass Cave Villa experience",
      "Destination address": "Beryl UT",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "5h30",
      "Plan / key stops": "Enjoy property, sunset; no Zion today",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "Confirmed"
    },
    {
      "Date": "29-Sep-2026",
      "Day": "Tue",
      "Start time": "08:00",
      "End time": "10:00",
      "Origin / departure point": "Outpost X",
      "Origin address": "",
      "Destination / activity": "Breakfast + checkout",
      "Destination address": "Beryl UT",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "2h",
      "Plan / key stops": "Use morning, checkout 10",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "Confirmed"
    },
    {
      "Date": "29-Sep-2026",
      "Day": "Tue",
      "Start time": "10:00",
      "End time": "11:30",
      "Origin / departure point": "Outpost X",
      "Origin address": "",
      "Destination / activity": "Drive to Zion",
      "Destination address": "Zion Visitor Center",
      "Drive time": "~1h30",
      "Drive distance (mi)": "65",
      "Buffer / activity time": "1h30",
      "Plan / key stops": "East Zion approach",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Outpost X drive estimate"
    },
    {
      "Date": "29-Sep-2026",
      "Day": "Tue",
      "Start time": "11:45",
      "End time": "14:30",
      "Origin / departure point": "Zion east",
      "Origin address": "",
      "Destination / activity": "Canyon Overlook + east Zion",
      "Destination address": "Canyon Overlook Trailhead",
      "Drive time": "~0h25",
      "Drive distance (mi)": "12",
      "Buffer / activity time": "2h45",
      "Plan / key stops": "Short hike + east Zion viewpoints",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "No shuttle required"
    },
    {
      "Date": "29-Sep-2026",
      "Day": "Tue",
      "Start time": "14:30",
      "End time": "15:00",
      "Origin / departure point": "Zion",
      "Origin address": "",
      "Destination / activity": "Drive + Hampton check-in",
      "Destination address": "1127 Zion Park Blvd",
      "Drive time": "~0h15",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "30m",
      "Plan / key stops": "Check-in from 15:00",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "Hilton official"
    },
    {
      "Date": "29-Sep-2026",
      "Day": "Tue",
      "Start time": "16:00",
      "End time": "18:00",
      "Origin / departure point": "Springdale",
      "Origin address": "",
      "Destination / activity": "Pa'rus / town walk",
      "Destination address": "Springdale / Zion",
      "Drive time": "local",
      "Drive distance (mi)": "3",
      "Buffer / activity time": "2h",
      "Plan / key stops": "Easy sunset activity",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Protect legs for long drive"
    },
    {
      "Date": "29-Sep-2026",
      "Day": "Tue",
      "Start time": "18:30",
      "End time": "19:45",
      "Origin / departure point": "Springdale",
      "Origin address": "",
      "Destination / activity": "Dinner",
      "Destination address": "Springdale",
      "Drive time": "local",
      "Drive distance (mi)": "1",
      "Buffer / activity time": "1h15",
      "Plan / key stops": "Oscar's / Bit & Spur / similar; verify hours",
      "Booking required?": "Optional",
      "Planned direct cost ($)": 0,
      "Status / action": "RECOMMENDED",
      "Source / note": "Flexible"
    },
    {
      "Date": "30-Sep-2026",
      "Day": "Wed",
      "Start time": "05:15",
      "End time": "05:45",
      "Origin / departure point": "Hampton",
      "Origin address": "",
      "Destination / activity": "Breakfast + pack",
      "Destination address": "1127 Zion Park Blvd",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "30m",
      "Plan / key stops": "Leave 06:00",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Long positioning day"
    },
    {
      "Date": "30-Sep-2026",
      "Day": "Wed",
      "Start time": "06:00",
      "End time": "08:35",
      "Origin / departure point": "Springdale",
      "Origin address": "",
      "Destination / activity": "Drive to Las Vegas area",
      "Destination address": "I-15",
      "Drive time": "~2h30–2h45",
      "Drive distance (mi)": "160",
      "Buffer / activity time": "2h35",
      "Plan / key stops": "Fuel only if needed",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Live navigation on day"
    },
    {
      "Date": "30-Sep-2026",
      "Day": "Wed",
      "Start time": "08:35",
      "End time": "09:00",
      "Origin / departure point": "Las Vegas",
      "Origin address": "",
      "Destination / activity": "Fuel + bathroom + coffee",
      "Destination address": "Las Vegas",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "25m",
      "Plan / key stops": "Fill tank",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Operational stop"
    },
    {
      "Date": "30-Sep-2026",
      "Day": "Wed",
      "Start time": "09:00",
      "End time": "13:00",
      "Origin / departure point": "Las Vegas",
      "Origin address": "",
      "Destination / activity": "Drive via US-95 / US-395",
      "Destination address": "Bishop CA",
      "Drive time": "~4h",
      "Drive distance (mi)": "210",
      "Buffer / activity time": "4h",
      "Plan / key stops": "Stretch as needed",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Route may vary"
    },
    {
      "Date": "30-Sep-2026",
      "Day": "Wed",
      "Start time": "13:00",
      "End time": "13:45",
      "Origin / departure point": "Bishop",
      "Origin address": "",
      "Destination / activity": "Lunch + fuel",
      "Destination address": "Bishop",
      "Drive time": "0",
      "Drive distance (mi)": "0",
      "Buffer / activity time": "45m",
      "Plan / key stops": "Simple lunch",
      "Booking required?": "No",
      "Planned direct cost ($)": 0,
      "Status / action": "LOCKED",
      "Source / note": "Operational stop"
    },
    {
      "Date": "30-Sep-2026",
      "Day": "Wed",
      "Start time": "13:45",
      "End time": "16:00",
      "Origin / departure point": "Bishop",
      "Origin address": "",
      "Destination / activity": "Drive + Mammoth check-in buffer",
      "Destination address": "10400 Minaret Rd",
      "Drive time": "~1h30–1h45",
      "Drive distance (mi)": "45",
      "Buffer / activity time": "2h15",
      "Plan / key stops": "Hotel check-in 16:00; early arrival may be possible",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "Official check-in 16:00"
    },
    {
      "Date": "30-Sep-2026",
      "Day": "Wed",
      "Start time": "16:00",
      "End time": "19:00",
      "Origin / departure point": "Mammoth",
      "Origin address": "",
      "Destination / activity": "Check-in + dinner + fuel",
      "Destination address": "Mammoth Lakes",
      "Drive time": "local",
      "Drive distance (mi)": "5",
      "Buffer / activity time": "3h",
      "Plan / key stops": "Fuel full; buy breakfast/snacks",
      "Booking required?": "YES",
      "Planned direct cost ($)": 0,
      "Status / action": "BOOKED",
      "Source / note": "$134 confirmed"
    }
  ],
  "bookings": [
    {
      "Order": 1,
      "Reservation": "Outpost X - Glass Cave Villa or Cave Villa",
      "Date": "28-Sep-2026",
      "Target time": "15:00 check-in; 10:00 check-out 29-Sep",
      "Party": "2",
      "Cost / budget": "BOOKED; price from confirmation not captured",
      "Where / meeting point": "Beryl, Utah",
      "Cancellation / timing": "Policy: >30 days full refund; 29-14 days 50%; <=13 days no refund",
      "Must reserve now?": "DONE",
      "Status": "BOOKED",
      "Source URL": "https://outpost-x.com/",
      "Notes": "Glass Cave Villa. Reservation #: 6aac63907ca7a30148530cf4. Confirmation: GY-EsUsPFnF."
    },
    {
      "Order": 2,
      "Reservation": "Upper Antelope Canyon",
      "Date": "26-Sep-2026",
      "Target time": "16:00–17:40",
      "Party": "2",
      "Cost / budget": "CONFIRMED; paid (exact total not captured here)",
      "Where / meeting point": "22 S Lake Powell Blvd, Page, AZ",
      "Cancellation / timing": "Timed tour; arrive early",
      "Must reserve now?": "DONE",
      "Status": "CONFIRMED",
      "Source URL": "https://lowerantelope.com/tours/",
      "Notes": "4x4 transport + Navajo guide; arrive by ~15:30."
    },
    {
      "Order": 3,
      "Reservation": "Lake Powell kayak tour",
      "Date": "26-Sep-2026",
      "Target time": "09:30–12:00",
      "Party": "2",
      "Cost / budget": "CONFIRMED; final paid total not captured here",
      "Where / meeting point": "910 Coppermine Rd / Antelope Public Launch Ramp, Page, AZ",
      "Cancellation / timing": "Timed; weather dependent",
      "Must reserve now?": "DONE",
      "Status": "CONFIRMED",
      "Source URL": "https://www.kayakpowell.com/guided-tours",
      "Notes": "Lower Antelope Canyon Discovery / kayak; double sit-on-top kayaks; equipment + dry bags."
    },
    {
      "Order": 4,
      "Reservation": "America the Beautiful Non-Resident Annual Pass",
      "Date": "By first park entry",
      "Target time": "Before Grand Canyon",
      "Party": "2",
      "Cost / budget": "$250",
      "Where / meeting point": "Digital Recreation.gov or park entrance",
      "Cancellation / timing": "Non-refundable; ID verification",
      "Must reserve now?": "DONE",
      "Status": "BOOKED",
      "Source URL": "https://www.nps.gov/planyourvisit/passes.htm",
      "Notes": "Purchased/confirmed by user."
    },
    {
      "Order": 5,
      "Reservation": "Best Western Plus Cedar City",
      "Date": "27-Sep-2026",
      "Target time": "1 night",
      "Party": "2",
      "Cost / budget": "BOOKED",
      "Where / meeting point": "Cedar City, UT",
      "Cancellation / timing": "Confirmed booking",
      "Must reserve now?": "DONE",
      "Status": "BOOKED",
      "Source URL": "https://www.bestwestern.com/",
      "Notes": "27→28 Sep. Replaces old Bryce-area hotel assumption."
    },
    {
      "Order": 6,
      "Reservation": "Springdale/Zion hotel",
      "Date": "29-Sep-2026",
      "Target time": "15:00 check-in; 11:00 check-out 30-Sep",
      "Party": "2",
      "Cost / budget": "$280 incl. taxes + fees",
      "Where / meeting point": "Springdale, UT",
      "Cancellation / timing": "Flexible cancellation preferred",
      "Must reserve now?": "DONE",
      "Status": "BOOKED",
      "Source URL": "https://www.booking.com/city/us/springdale-utah.html",
      "Notes": "Hampton Inn & Suites Springdale/Zion National Park. Booking ID 1056565474."
    },
    {
      "Order": 7,
      "Reservation": "Mammoth Mountain Inn",
      "Date": "30-Sep-2026",
      "Target time": "30-Sep → 01-Oct",
      "Party": "2",
      "Cost / budget": "$134 incl. taxes + fees",
      "Where / meeting point": "10400 Minaret Road, Mammoth Lakes, CA 93546",
      "Cancellation / timing": "Free cancellation selected at booking",
      "Must reserve now?": "DONE",
      "Status": "BOOKED",
      "Source URL": "https://www.mammothmountain.com/plan-your-trip/mammoth-hotels/mammoth-mountain-inn",
      "Notes": "Double Room. Confirmation 17997421836957808616."
    },
    {
      "Order": 8,
      "Reservation": "Coast Burbank Hotel",
      "Date": "01-03 Oct 2026",
      "Target time": "2 nights",
      "Party": "2",
      "Cost / budget": "$228.65 Oct 1 + $249.05 Oct 2 room rates; parking $25/night",
      "Where / meeting point": "Burbank, CA",
      "Cancellation / timing": "Confirmed",
      "Must reserve now?": "DONE",
      "Status": "BOOKED",
      "Source URL": "https://www.coasthotels.com/",
      "Notes": "Confirmation 1102922474; check-in 1-Oct 15:00, check-out 3-Oct 11:00."
    },
    {
      "Order": 9,
      "Reservation": "Universal Studios Hollywood",
      "Date": "02-Oct-2026",
      "Target time": "Full day",
      "Party": "2",
      "Cost / budget": "$218+ General Admission; actual paid amount per confirmation",
      "Where / meeting point": "100 Universal City Plaza, Universal City, CA",
      "Cancellation / timing": "Date-specific pricing",
      "Must reserve now?": "DONE",
      "Status": "BOOKED",
      "Source URL": "https://store.universalstudioshollywood.com/",
      "Notes": "Purchased/confirmed by user for 02-Oct-2026."
    },
    {
      "Order": 10,
      "Reservation": "South Point Hotel Casino and Spa",
      "Date": "30-Sep-2026",
      "Target time": "1 night",
      "Party": "2",
      "Cost / budget": "CANCELLED",
      "Where / meeting point": "Las Vegas, NV",
      "Cancellation / timing": "Cancelled by user 20-Sep",
      "Must reserve now?": "DONE",
      "Status": "CANCELLED",
      "Source URL": "https://southpointcasino.com/",
      "Notes": "Superseded by Mammoth Mountain Inn to preserve Yosemite route."
    },
    {
      "Order": 11,
      "Reservation": "Optional Halloween Horror Nights",
      "Date": "02-Oct-2026",
      "Target time": "~19:00 onward",
      "Party": "2",
      "Cost / budget": "$TBD",
      "Where / meeting point": "Universal Studios Hollywood",
      "Cancellation / timing": "Separate ticket; intense horror content",
      "Must reserve now?": "OPTIONAL",
      "Status": "Not booked",
      "Source URL": "https://www.universalstudioshollywood.com/hhn",
      "Notes": "Optional only."
    },
    {
      "Order": 11,
      "Reservation": "Bryce Canyon park entry",
      "Date": "27-Sep-2026",
      "Target time": "Before park entry",
      "Party": "2",
      "Cost / budget": "Covered by purchased annual pass",
      "Where / meeting point": "Bryce Canyon National Park, UT",
      "Cancellation / timing": "No timed entry required",
      "Must reserve now?": "DONE",
      "Status": "COVERED",
      "Source URL": "https://www.nps.gov/brca/planyourvisit/fees.htm",
      "Notes": "Entry covered by the purchased America the Beautiful Non-Resident Annual Pass."
    },
    {
      "Order": 12,
      "Reservation": "Rental car - Las Vegas to LAS return",
      "Date": "24-Sep-2026",
      "Target time": "09:00 pickup; 04-Oct 14:00 return",
      "Party": 2,
      "Cost / budget": "User booking; exact total not captured",
      "Where / meeting point": "Harry Reid Airport / LAS",
      "Cancellation / timing": "Return 04-Oct 14:00",
      "Must reserve now?": "DONE",
      "Status": "BOOKED",
      "Source URL": null,
      "Notes": "Rental car remains with father through 04-Oct; 22-23 Sep are car-free."
    },
    {
      "Order": 13,
      "Reservation": "Studio 6 Suites LAX",
      "Date": "03-Oct-2026",
      "Target time": "After 23:15 / overnight",
      "Party": 1,
      "Cost / budget": "Booked; exact total per confirmation",
      "Where / meeting point": "5101 West Century Boulevard, Los Angeles, CA 90045",
      "Cancellation / timing": "03-Oct check-in / 04-Oct check-out",
      "Must reserve now?": "DONE",
      "Status": "BOOKED",
      "Source URL": null,
      "Notes": "Booking ID 1056218566; father overnight after Omer departs."
    },
    {
      "Order": 14,
      "Reservation": "Dig This Las Vegas",
      "Date": "23-Sep-2026",
      "Target time": "08:00 slot",
      "Party": 2,
      "Cost / budget": "$28 pp incl. tax/fees",
      "Where / meeting point": "3012 S Rancho Dr, Las Vegas, NV 89102",
      "Cancellation / timing": "Timed slot; current availability found",
      "Must reserve now?": "RECOMMENDED",
      "Status": "NOT BOOKED",
      "Source URL": "https://www.digthisvegas.com/",
      "Notes": "Short hands-on physical activity before 14:00 Sphere; book only if desired."
    }
  ],
  "notes": [
    "23/9 morning: Dig This remains optional / not booked; Sphere is confirmed at 14:00.",
    "24/9 rental pickup at LAS is 09:00; road day to Grand Canyon follows.",
    "30/9 is the longest driving day: Zion → Las Vegas/Bishop → Mammoth.",
    "1/10 depends on Tioga Road being open; verify before leaving Mammoth.",
    "Omer flies from LAX on 3/10; father stays near LAX overnight at Studio 6 Suites.",
    "Rental car returns at LAS on 4/10 at 14:00."
  ]
};
